# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e22016537b2015ad7ee882507925ed23dc776bb1b038ae8068a5850db626eadd1fffdc0eebb60f4ba62dcc1232663a62a7a61b5ca3c50bf579b958b78d66022a

test:
  secret_key_base: 8885bf06107e14c11f4549a53ddce64a72e27806826d5c8ba7701f8d9a8b9572c2458650046d92da15f228fdc8afdbaef2df56e71bee88c97241a0483174581e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
